repositoryUrl: https://github.com/bbongTest1/bbongTest1.github.io/blob/master

docHomePage: /

introduction: /introduction/
c_cplusplus: /programming/c-cplusplus/
parameters: /
enhancements: /enhancements/

parameters_reference: /parameters/reference/
enumerations: /parameters/reference/enum/
structs: /programming/c-cplusplus/api-reference/struct/
cpp_methods: /programming/c-cplusplus/api-reference/cpp-method/
c_methods: /programming/c-cplusplus/api-reference/c-method/


dynamsoft_logo: /assets/img-icon/dynamsoft-logo.png
dbr_logo: /assets/img-icon/dbr-logo.png
edit_icon: /assets/img-icon/edit-icon.png