repositoryUrl: https://github.com/bbongTest1/bbongTest1.github.io/blob/master

docHomePage: /

introduction: /introduction/

dynamsoft_logo: /assets/img-icon/dynamsoft_logo.png
dbr_logo: /assets/img-icon/dbr_logo.png
edit_icon: /assets/img-icon/edit_icon.png